Repository genexuslabs/chameleon-controls-library, pull requests merged in 2023-07, with the labels that each got.

#74 Update to Stencil 2.17.0
  package-lock.json
  package.json
  src/components.d.ts
Labels: feature

#75 Add support for adding entities in data modeling control
  src/components.d.ts
  src/components/next/data-modeling-item/next-data-modeling-item.scss
  src/components/next/data-modeling-item/next-data-modeling-item.tsx
  src/components/next/data-modeling-item/readme.md
Labels: fix, feature

#73 Component/suggest
  src/components.d.ts
  src/components/suggest/ch-suggest.scss
  src/components/suggest/ch-suggest.tsx
  src/components/suggest/notes.txt
  src/components/suggest/readme.md
  src/components/suggest/suggest-list-item/ch-suggest-list-item.scss
  src/components/suggest/suggest-list-item/ch-suggest-list-item.tsx
  src/components/suggest/suggest-list-item/readme.md
  src/components/suggest/suggest-list-item/test/ch-suggest-list-item.e2e.ts
  src/components/suggest/suggest-list-item/test/ch-suggest-list-item.spec.tsx
  src/components/suggest/suggest-list/ch-suggest-list.scss
  src/components/suggest/suggest-list/ch-suggest-list.tsx
  src/components/suggest/suggest-list/readme.md
  src/components/suggest/suggest-list/test/ch-suggest-list.e2e.ts
  src/components/suggest/suggest-list/test/ch-suggest-list.spec.tsx
  src/components/suggest/test/ch-suggest.e2e.ts
  src/components/suggest/test/ch-suggest.spec.tsx
  src/components/window/readme.md
  src/index.html
  src/pages/accordion.html
  src/pages/assets/apple.svg
  src/pages/assets/ch.ico
  src/pages/assets/common.js
  src/pages/assets/styles.css
  src/pages/checkbox.html
  src/pages/common.js
  src/pages/drag-bar.html
  src/pages/dropdown.html
  src/pages/grid.html
  src/pages/icon.html
  src/pages/notifications.html
  src/pages/paginator.html
  src/pages/qr.html
  src/pages/select.html
  src/pages/sidebar.html
  src/pages/step-list.html
  src/pages/suggest.html
  src/pages/tree.html
  src/pages/window.html
Labels: feature

#78 Update components.d.ts
  src/components.d.ts
Labels: fix

#77 Add ch-entity-selector control
  src/components.d.ts
  src/components/entity-selector/ch-entity-selector.scss
  src/components/entity-selector/ch-entity-selector.tsx
  src/components/entity-selector/readme.md
  src/components/icon/readme.md
  src/index.html
  src/pages/1px-square.svg
  src/pages/close.svg
  src/pages/datastore.svg
  src/pages/entity-selector.html
  src/pages/knowledge-base.svg
  src/pages/patterns.svg
  src/pages/show-more-horizontal.svg
Labels: feature

#81 Update interfaces
  src/components.d.ts
  src/components/entity-selector/readme.md
Labels: documentation

#82 Update and improve ESLint rules
  .eslintplugin.js
  .eslintrc.js
  package-lock.json
  package.json
Labels: documentation, feature
