Repository genexuslabs/chameleon-controls-library, pull requests merged in 2023-09, with the labels that each got.

#125 [ch-window] Update listeners suscription
  src/components/window/ch-window.tsx
Labels: fix

#126 Add ch-style component to style chameleon components
  src/components.d.ts
  src/components/grid/ch-grid-manager.ts
  src/components/style/ch-global-stylesheet.ts
  src/components/style/ch-style.scss
  src/components/style/ch-style.tsx
  src/components/style/readme.md
  src/components/window/ch-window.tsx
  src/index.html
  src/pages/style.css
  src/pages/style.html
Labels: feature

#129 Add a new implementation for the Tree View control
  src/common/interfaces.ts
  src/common/reserverd-names.ts
  src/components.d.ts
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
  src/components/common/helpers.ts
  src/components/test/helpers.ts
  src/components/test/readme.md
  src/components/test/test-tree-x.scss
  src/components/test/test-tree-x.tsx
  src/components/test/types.ts
  src/components/tree-x-list-item/readme.md
  src/components/tree-x-list-item/tree-x-list-item.scss
  src/components/tree-x-list-item/tree-x-list-item.tsx
  src/components/tree-x-list/readme.md
  src/components/tree-x-list/tree-x-list.scss
  src/components/tree-x-list/tree-x-list.tsx
  src/components/tree-x/readme.md
  src/components/tree-x/tree-x.scss
  src/components/tree-x/tree-x.tsx
  src/components/tree-x/types.ts
  src/pages/tree.html
  stencil.config.ts
Labels: feature

#135 Fixes for ch-window
  src/components/window/ch-window.scss
  src/components/window/ch-window.tsx
Labels: fix

#137 Fixes and improvements for the ch-dropdown control
  src/components/dropdown-item-separator/readme.md
  src/components/dropdown-item/dropdown-item.scss
  src/components/dropdown-item/dropdown-item.tsx
  src/components/dropdown-item/readme.md
  src/components/dropdown/_dropdown-tokens.scss
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/readme.md
  src/components/dropdown/types.ts
  src/components/test/test-dropdown/test-dropdown.scss
  src/components/test/test-dropdown/test-dropdown.tsx
  src/components/test/test-dropdown/types.ts
  src/pages/dropdown.html
Labels: fix, feature

#139 Fixes for ch-dropdown and ch-action-group
  src/components.d.ts
  src/components/action-group-item/action-group-item.tsx
  src/components/action-group-item/readme.md
  src/components/action-group/action-group.scss
  src/components/action-group/action-group.tsx
  src/components/dropdown-item/dropdown-item.scss
  src/components/dropdown-item/dropdown-item.tsx
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.tsx
  src/components/test/test-action-group/test-action-group.tsx
Labels: fix

#141 Improve ch-action-group rendering performance
  src/components.d.ts
  src/components/action-group-item/action-group-item.scss
  src/components/action-group/action-group.tsx
  src/components/dropdown-item/dropdown-item.scss
  src/components/dropdown-item/dropdown-item.tsx
  src/components/dropdown/dropdown.tsx
  src/components/window/ch-window.tsx
  src/components/window/readme.md
Labels: fix, feature

#142 Fixes for dropdown opening
  src/components.d.ts
  src/components/action-group-item/action-group-item.tsx
  src/components/action-group-item/readme.md
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/readme.md
  src/components/test/test-action-group/test-action-group.tsx
  src/components/window/ch-window.scss
  src/components/window/ch-window.tsx
  src/components/window/readme.md
Labels: fix

#143 Improve the implementation of the Tree View control
  src/common/scroll-to-edge.ts
  src/common/types.ts
  src/components/checkbox/checkbox.scss
  src/components/test/test-tree-x.scss
  src/components/test/test-tree-x.tsx
  src/components/tree-x-list-item/tree-x-list-item.scss
  src/components/tree-x-list-item/tree-x-list-item.tsx
  src/components/tree-x-list/tree-x-list.tsx
  src/components/tree-x/tree-x.scss
  src/components/tree-x/tree-x.tsx
  src/components/tree-x/types.ts
  src/pages/tree.html
Labels: fix, feature
