Repository genexuslabs/chameleon-controls-library, pull requests merged in 2023-08, with the labels that each got.

#89 Add ch-textblock control
  src/common/_base.scss
  src/common/line-clamp.ts
  src/common/reserverd-names.ts
  src/common/utils.ts
  src/components/textblock/readme.md
  src/components/textblock/textblock.scss
  src/components/textblock/textblock.tsx
  src/index.html
  src/pages/textblock.html
Labels: feature

#91 Improve ch-window control implementation
  src/components/window/ch-window.tsx
  src/components/window/readme.md
Labels: fix, feature

#94 Fixes and improvements for ch-window control
  src/components/window/ch-window.scss
  src/components/window/ch-window.tsx
  src/components/window/window-close/ch-window-close.tsx
Labels: fix, feature

#99 Add tooltip in ch-textblock control when the content is trimmed
  src/common/line-clamp.ts
  src/components/textblock/textblock.tsx
  src/pages/textblock.html
Labels: feature

#112 Ch suggest fix focus
  src/common/types.ts
  src/components.d.ts
  src/components/suggest/ch-suggest.scss
  src/components/suggest/ch-suggest.tsx
  src/components/suggest/readme.md
  src/components/suggest/suggest-list-item/ch-suggest-list-item.scss
  src/components/suggest/suggest-list-item/ch-suggest-list-item.tsx
  src/components/suggest/suggest-list-item/readme.md
  src/components/suggest/suggest-list/ch-suggest-list.tsx
  src/components/textblock/readme.md
  src/components/tree-item/readme.md
  src/components/tree/readme.md
  src/components/window/readme.md
  src/pages/suggest.html
Labels: fix

#114 Ch suggest/fixes
  src/components.d.ts
  src/components/suggest/ch-suggest.scss
  src/components/suggest/ch-suggest.tsx
  src/components/suggest/readme.md
  src/components/suggest/suggest-list-item/ch-suggest-list-item.scss
  src/components/suggest/suggest-list-item/ch-suggest-list-item.tsx
  src/components/suggest/suggest-list-item/readme.md
  src/components/suggest/suggest-list/ch-suggest-list.scss
  src/pages/suggest.html
Labels: fix
