Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-04, with the labels that each got.

#262 Add `ch-combo-box` control
  src/common/_base.scss
  src/common/interfaces.ts
  src/common/reserverd-names.ts
  src/common/utils.ts
  src/components.d.ts
  src/components/combobox/combo-box.scss
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/components/combobox/types.ts
  src/components/dropdown/dropdown.scss
  src/showcase/models/components.js
  src/showcase/pages/combo-box.html
Labels: feature, target: minor

#263 Add support for customizing exported parts in dropdown and action-group controls
  src/common/reserverd-names.ts
  src/components.d.ts
  src/components/action-group/action-group/action-group.tsx
  src/components/dropdown/dropdown.tsx
  src/components/renders/action-group/action-group-render.tsx
  src/components/renders/action-group/readme.md
  src/components/renders/dropdown/dropdown-render.tsx
  src/components/renders/dropdown/readme.md
Labels: feature, target: minor

#264 Add `ch-sidebar` control and other improvements
  src/components/layout-splitter/layout-splitter.scss
  src/components/layout-splitter/layout-splitter.tsx
  src/components/list/list.scss
  src/components/renders/tree-view/tree-view-render.tsx
  src/components/renders/tree-view/types.ts
  src/components/sidebar/expanded-change-obervables.ts
  src/components/sidebar/sidebar.scss
  src/components/sidebar/sidebar.tsx
  src/showcase/models/components.js
  src/showcase/pages/sidebar-old.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/tree.html
Labels: fix, feature, target: minor, performance

#261 Add `ch-dialog` control
  package-lock.json
  src/components.d.ts
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
  src/components/dialog/types.ts
  src/components/dropdown/readme.md
  src/components/popover/readme.md
  src/components/renders/action-group/readme.md
  src/components/renders/tree-view/readme.md
  src/components/sidebar/readme.md
  src/showcase/models/components.js
  src/showcase/pages/dialog.html
Labels: feature, target: minor

#265 Add support for `dragOutsideDisabled` and `sortable` in `ch-list` and `ch-flexible-layout-render` controls
  src/components.d.ts
  src/components/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/types.ts
  src/components/list/list.scss
  src/components/list/list.tsx
  src/components/list/readme.md
  src/components/renders/flexible-layout/utils.ts
  src/components/test/test-flexible-layout/renders.tsx
Labels: feature, target: minor

#266 Rename 5.0.0-beta.10 to 5.1.0
  src/index.html
Labels: documentation

#267 Add `box-sizing: border-box` in tab buttons (`ch-list` control)
  src/components/list/list.scss
Labels: fix, target: patch

#269 Fix browser's crashes in `ch-dropdown` control and reduce initial flickering
  src/components/dropdown/dropdown.tsx
  src/components/popover/popover.scss
  src/components/popover/popover.tsx
  src/components/popover/readme.md
Labels: fix, target: patch

#268 Fixes and improvements for `ch-dialog` control
  src/components.d.ts
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
Labels: fix, feature, target: minor, accessibility

#271 Facilitate the styling of the `ch-dropdown` control
  src/common/reserverd-names.ts
  src/components.d.ts
  src/components/action-group/action-group/action-group.tsx
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.tsx
  src/components/popover/popover.scss
  src/components/renders/dropdown/dropdown-render.tsx
  src/components/renders/dropdown/readme.md
  src/showcase/pages/dropdown.html
Labels: feature, target: minor, refactoring

#272 Add support to display a footer in `ch-dialog` control
  src/components.d.ts
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
  src/showcase/pages/dialog.html
Labels: feature, target: minor

#273 Add support for Shadow DOM in `ch-slider`
  src/components.d.ts
  src/components/slider/readme.md
  src/components/slider/slider.scss
  src/components/slider/slider.tsx
  src/showcase/pages/slider.html
Labels: feature, target: minor

#274 Fix custom var names in `ch-slider`
  src/components/slider/slider.scss
Labels: fix, target: patch

#275 Add `ch-radio-group-render` control
  src/common/reserverd-names.ts
  src/components.d.ts
  src/components/renders/radio-group/radio-group-render.scss
  src/components/renders/radio-group/radio-group-render.tsx
  src/components/renders/radio-group/readme.md
  src/components/renders/radio-group/types.ts
  src/showcase/models/components.js
  src/showcase/pages/radio-group.html
Labels: feature, target: minor

#276 Fixes and improvements for `ch-checkbox` control
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
Labels: fix, feature, target: minor

#277 Fixes for Tree View, Slider, Combo Box and Segmented Control
  src/components/combobox/combo-box.tsx
  src/components/renders/segmented-control/segmented-control-render.tsx
  src/components/slider/slider.tsx
  src/components/tree-view/tree-view-item/tree-view-item.scss
Labels: fix, target: patch

#279 Make the ESLint and TypeScript more strict
  .eslintrc.js
  src/common/utils.ts
  src/components.d.ts
  src/components/action-group/test/action-group.e2e.ts
  src/components/grid/ch-grid-manager-column-resize.ts
  src/components/grid/ch-grid-manager-columns.ts
  src/components/grid/ch-grid-manager.ts
  src/components/grid/ch-grid.tsx
  src/components/grid/grid-rowset/ch-grid-rowset.tsx
  src/components/grid/readme.md
  src/components/gx-grid/gx-grid-chameleon.tsx
  src/components/gx-grid/gx-grid-column-filter/gx-grid-chameleon-column-filter.tsx
  src/components/next/data-modeling-item/next-data-modeling-item.tsx
  src/components/paginator/paginator-pages/ch-paginator-pages.tsx
  src/components/renders/tree-view/genexus-implementation.ts
  src/components/shortcuts/ch-shortcuts-manager.ts
  src/components/shortcuts/ch-shortcuts.tsx
  src/components/sidebar/expanded-change-obervables.ts
  src/components/suggest/ch-suggest.tsx
  src/components/suggest/suggest-list-item/ch-suggest-list-item.tsx
  src/components/suggest/suggest-list-item/test/ch-suggest-list-item.e2e.ts
  src/components/suggest/suggest-list/test/ch-suggest-list.e2e.ts
  src/components/suggest/test/ch-suggest.e2e.ts
  src/deprecated-components/form-checkbox/ch-form-checkbox.tsx
  src/deprecated-components/icon/requests.ts
  src/deprecated-components/select-item/ch-select-option.tsx
  src/deprecated-components/select/ch-select.tsx
  src/deprecated-components/sidebar-menu-list-item/ch-sidebar-menu-list-item.tsx
  src/deprecated-components/sidebar-menu-list/ch-sidebar-menu-list.tsx
  src/deprecated-components/sidebar-menu/ch-sidebar-menu.tsx
  src/deprecated-components/step-list-item/ch-step-list-item.tsx
  src/deprecated-components/tree-item/ch-tree-item.tsx
  src/deprecated-components/tree/ch-tree.tsx
  src/helpers/storage-helper.ts
  tsconfig.json
Labels: documentation, fix, target: major, breaking changes, refactoring

#280 Fix ESLint issues
  src/components/markdown/parsers/markdown-to-jsx.tsx
  src/components/markdown/parsers/raw-html-to-jsx.tsx
  src/components/next/progress-bar/next-progress-bar.tsx
  src/components/renders/flexible-layout/flexible-layout-render.tsx
Labels: target: patch

#281 Update showcase version to 6.0.0-next.0
  src/index.html
Labels: documentation, target: patch

#282 Use the latest minor and patch versions
  package-lock.json
  package.json
  src/components/list/list.tsx
Labels: target: patch, dependencies

#284 Add the `selectedId` in the rendered pages on initial load for `ch-list`
  src/components/list/list.tsx
Labels: fix, target: patch

#285 Add support to close the `ch-popover` when clicking outside in "manual" mode. Set by default "auto" mode
  src/components.d.ts
  src/components/popover/popover.tsx
  src/components/popover/readme.md
Labels: fix, target: patch

#286 Add `ch-code-editor` control
  .eslintrc.cjs
  .gitignore
  package-lock.json
  package.json
  src/components.d.ts
  src/components/code-editor/code-editor.scss
  src/components/code-editor/code-editor.tsx
  src/components/code-editor/monaco-styles-after-build.scss
  src/components/code-editor/monaco/monaco.ts
  src/components/code-editor/monaco/yaml.worker.ts
  src/components/code-editor/readme.md
  src/showcase/models/components.js
  src/showcase/pages/code-editor.html
  stencil.config.ts
  tsconfig.json
  vite.config.ts
Labels: feature, target: major, breaking changes, risky

#287 Add `build.monaco` script
  package.json
  src/showcase/pages/code-editor.html
Labels: feature, target: minor

#289 Improve responsiveness in `ch-popover` control
  src/components.d.ts
  src/components/popover/popover.tsx
  src/components/popover/readme.md
  src/components/popover/types.ts
  src/components/popover/utils.ts
  src/showcase/pages/popover.html
Labels: fix, feature, target: minor, accessibility

#290 Avoid FOUC (Flash Of Unstyled Content) in showcase
  src/index.html
  src/showcase/pages/accordion.html
  src/showcase/pages/action-group.html
  src/showcase/pages/alert.html
  src/showcase/pages/barcode-scanner.html
  src/showcase/pages/checkbox.html
  src/showcase/pages/code-editor.html
  src/showcase/pages/combo-box.html
  src/showcase/pages/dialog.html
  src/showcase/pages/dropdown.html
  src/showcase/pages/flexible-layout.html
  src/showcase/pages/grid.html
  src/showcase/pages/layout-splitter.html
  src/showcase/pages/markdown.html
  src/showcase/pages/notifications.html
  src/showcase/pages/paginator.html
  src/showcase/pages/popover.html
  src/showcase/pages/qr.html
  src/showcase/pages/radio-group.html
  src/showcase/pages/segmented-control.html
  src/showcase/pages/shortcuts.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/slider.html
  src/showcase/pages/tab.html
  src/showcase/pages/textblock.html
  src/showcase/pages/tooltip.html
  src/showcase/pages/tree.html
Labels: fix, target: patch

#291 Reduce memory consumption and event handlers in Tree View control
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
Labels: feature, target: minor, performance
