Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-09, with the labels that each got.

#405 Fix `ch-navigation-list-render`'s chevron direction
  src/components/navigation-list/internal/navigation-list-item/navigation-list-item.scss
  src/components/navigation-list/internal/navigation-list-item/navigation-list-item.tsx
Labels: fix

#406 Add support to determine the expanded size of the `ch-accordion-render` items
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.tsx
  src/components/accordion/readme.md
  src/components/accordion/tests/accordion.e2e.ts
  src/components/accordion/tests/expanded-size.e2e.ts
  src/components/accordion/types.ts
  src/showcase/assets/components/accordion/accordion.showcase.tsx
  src/showcase/assets/components/accordion/models.ts
Labels: feature, target: minor, breaking changes

#407 Fixes for the `ch-edit` component
  src/components/edit/edit.scss
  src/components/edit/edit.tsx
  src/components/edit/tests/edit.e2e.ts
  src/components/edit/tests/form.e2e.ts
  src/showcase/assets/components/pages.ts
  src/testing/form.e2e.ts
Labels: fix, target: patch, accessibility

#408 Fixes and improvements for the `ch-chat`
  src/components.d.ts
  src/components/chat/chat.tsx
  src/components/chat/readme.md
  src/components/code/code.tsx
  src/components/smart-grid/smart-grid.scss
  src/components/smart-grid/smart-grid.tsx
  src/index.html
  src/virtual-scroller/cells-in-viewport-are-rendered-and-visible.ts
  src/virtual-scroller/get-new-start-and-end-indexes.ts
  src/virtual-scroller/readme.md
  src/virtual-scroller/types.ts
  src/virtual-scroller/update-virtual-scroll.ts
  src/virtual-scroller/utils.ts
  src/virtual-scroller/virtual-scroller.scss
  src/virtual-scroller/virtual-scroller.tsx
Labels: fix, feature, target: minor

#409 Fixes and improvements for the `ch-navigation-list-render` component
  src/common/utils.ts
  src/components.d.ts
  src/components/edit/tests/edit.e2e.ts
  src/components/navigation-list/navigation-list-render.tsx
  src/components/navigation-list/readme.md
  src/components/navigation-list/types.ts
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/showcase/assets/components/accordion/models.ts
  src/showcase/assets/components/edit/models.ts
  src/showcase/assets/components/image/models.ts
  src/showcase/assets/components/navigation-list/navigation-list.showcase.tsx
  src/showcase/assets/components/sidebar/sidebar.showcase.tsx
  src/showcase/assets/components/tree-view/models.ts
  src/showcase/base.css
  stencil.config.ts
Labels: fix, target: patch

#410 Improve property names and values in the `ch-navigation-list-render`
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/navigation-list/internal/navigation-list-item/navigation-list-item.scss
  src/components/navigation-list/internal/navigation-list-item/navigation-list-item.tsx
  src/components/navigation-list/internal/navigation-list-item/readme.md
  src/components/navigation-list/navigation-list-render.scss
  src/components/navigation-list/navigation-list-render.tsx
  src/components/navigation-list/readme.md
  src/showcase/assets/components/navigation-list/navigation-list.showcase.tsx
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/sidebar/sidebar.showcase.tsx
Labels: target: patch, breaking changes

#411 Fixes and improvements for the `ch-chat` implementation
  src/components.d.ts
  src/components/chat/chat.scss
  src/components/chat/chat.tsx
  src/components/chat/default-chat-render.tsx
  src/components/chat/readme.md
  src/components/chat/types.ts
  src/components/markdown-viewer/markdown-viewer.tsx
  src/components/markdown-viewer/readme.md
  src/index.html
  src/showcase/assets/components/chat/callbacks.ts
  src/showcase/assets/components/chat/chat.showcase.tsx
  src/showcase/assets/components/chat/mercury-code-render.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/base.css
Labels: fix, feature

#412 Fix race condition when adding a new message
  src/components/chat/chat.tsx
Labels: fix, target: patch

#414 The trigger moment for the rowClicked event of the TabularGrid is changed
  src/components/tabular-grid/cell/tabular-grid-cell.ts
  src/components/tabular-grid/tabular-grid.tsx
  src/deprecated-components/grid/ch-grid.tsx
Labels: bug, target: major, breaking changes

#415 Improve readme
  README.md
Labels: documentation

#416 Improve the style of the showcase
  src/components/test/test-flexible-layout/test-action-group-styles.scss
  src/components/test/test-flexible-layout/test-flexible-layout.scss
  src/showcase/assets/components/markdown/markdown.showcase.tsx
  src/showcase/assets/components/showcase.scss
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/slider/slider.showcase.tsx
  src/showcase/base.css
Labels: showcase

#417 `[ch-edit]` Add `debounce` property to support debouncing the input event
  src/components.d.ts
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/debounce.e2e.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
Labels: feature, target: minor

#418 Fix flaky tests
  src/components/edit/tests/debounce.e2e.ts
Labels: fix

#419 `[ch-radio-group-render]` Add support to specify the direction of the radio group items
  src/components.d.ts
  src/components/radio-group/radio-group-render.scss
  src/components/radio-group/radio-group-render.tsx
  src/components/radio-group/readme.md
  src/showcase/assets/components/radio-group/radio-group.showcase.tsx
Labels: feature, target: minor, breaking changes

#420 `[Showcase]` Remove default values in code examples and add "Usage (React)" section
  src/components/image/image.tsx
  src/components/popover/popover.tsx
  src/showcase/assets/components/accordion/accordion.showcase.tsx
  src/showcase/assets/components/barcode-scanner/barcode-scanner.showcase.tsx
  src/showcase/assets/components/chat/chat.showcase.tsx
  src/showcase/assets/components/checkbox/checkbox.showcase.tsx
  src/showcase/assets/components/code/code.showcase.tsx
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/dialog/dialog.showcase.tsx
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/assets/components/image/image.showcase.tsx
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/navigation-list/navigation-list.showcase.tsx
  src/showcase/assets/components/popover/popover.showcase.tsx
  src/showcase/assets/components/qr/qr.showcase.tsx
  src/showcase/assets/components/radio-group/radio-group.showcase.tsx
  src/showcase/assets/components/renders.ts
  src/showcase/assets/components/segmented-control/segmented-control.showcase.tsx
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/sidebar/sidebar.showcase.tsx
  src/showcase/assets/components/slider/slider.showcase.tsx
  src/showcase/assets/components/switch/switch.showcase.tsx
  src/showcase/assets/components/tab/tab.showcase.tsx
  src/showcase/assets/components/tooltip/tooltip.showcase.tsx
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/assets/components/utils.ts
Labels: showcase

#421 Improve the styling with the Mercury DS
  src/components/test/test-flexible-layout/renders.tsx
  src/showcase/assets/components/landing.tsx
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/renders.ts
  src/showcase/base.css
  src/showcase/index.css
Labels: showcase

#422 `[ch-edit]` Reflect `disabled` property to improve disabled styling
  src/components/edit/edit.tsx
  src/components/edit/tests/disabled.e2e.ts
Labels: feature, target: minor

#423 `[ch-edit]` Refactor `picture` property implementation
  package-lock.json
  package.json
  src/components.d.ts
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/disabled.e2e.ts
  src/components/edit/tests/picture.e2e.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/assets/components/edit/models.ts
  src/showcase/assets/components/renders.ts
Labels: fix, target: patch, breaking changes, refactoring, dependencies

#424 `[ch-edit]` Improve `ch-edit`'s interface default values
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/edit.e2e.ts
Labels: target: patch, breaking changes
