Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-05, with the labels that each got.

#292 Full support for Shadow DOM in Tree View control and refactor all part names
  src/common/reserverd-names.ts
  src/common/utils.ts
  src/components.d.ts
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/types.ts
  src/components/tree-view/internal/tree-view-item/readme.md
  src/components/tree-view/internal/tree-view-item/tree-view-item.scss
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/components/tree-view/internal/tree-view/readme.md
  src/components/tree-view/internal/tree-view/tree-view.scss
  src/components/tree-view/internal/tree-view/tree-view.tsx
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.scss
  src/components/tree-view/tree-view-render.tsx
  src/components/tree-view/types.ts
  src/components/tree-view/utils.ts
  src/showcase/pages/assets/models/tree.js
  src/showcase/pages/tree.html
Labels: documentation, fix, feature, target: major, accessibility, performance, refactoring, risky

#293 Improve accessibility in the `ch-checkbox` control and improve control customization
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
Labels: fix, feature, target: minor, accessibility

#294 Automatically update the Chameleon npm version in the showcase
  src/index.html
Labels: showcase

#296 Remove unused properties in `ch-tree-view-render` control
  src/components.d.ts
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.tsx
Labels: fix, target: patch

#297 Fixes and improvements for combo-box control
  src/components.d.ts
  src/components/combobox/combo-box.scss
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/showcase/pages/combo-box.html
Labels: fix, feature, target: minor, accessibility, performance

#299 Add missing page for Tree View
  src/showcase/pages/tree-view.html
Labels: target: patch, broken, showcase

#300 Improve UX when resizing sections in the `ch-layout-splitter` control
  src/common/types.ts
  src/common/utils.ts
  src/components.d.ts
  src/components/checkbox/readme.md
  src/components/combobox/readme.md
  src/components/dropdown/readme.md
  src/components/flexible-layout/readme.md
  src/components/layout-splitter/layout-splitter.scss
  src/components/layout-splitter/layout-splitter.tsx
  src/components/layout-splitter/readme.md
  src/components/layout-splitter/types.ts
  src/components/layout-splitter/utils.ts
  src/components/next/data-modeling-item/readme.md
  src/components/next/data-modeling-render/readme.md
  src/components/radio-group/readme.md
  src/components/tree-view/readme.md
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/layout-splitter/models.ts
  src/showcase/assets/components/showcase/readme.md
  src/showcase/assets/components/showcase/showcase-stories.ts
  src/showcase/assets/components/showcase/types.ts
  src/showcase/pages/layout-splitter.html
Labels: fix, target: patch, showcase

#302 Add support for filters on the server in `ch-combo-box` control and improve its responsiveness
  src/components.d.ts
  src/components/combobox/combo-box.tsx
  src/components/combobox/helpers.ts
  src/components/combobox/readme.md
  src/components/combobox/types.ts
Labels: feature, target: major, breaking changes

#303 Add support to render "object" type properties in the `ch-showcase` control and improve stories
  src/showcase/assets/components/checkbox/checkbox.showcase.tsx
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
  src/showcase/assets/components/dropdown/dropdown.showcase.tsx
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/showcase.scss
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/showcase/showcase-stories.ts
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/pages/combo-box.html
Labels: target: patch, showcase

#301 [ch-grid] Fix errors related to selection
  src/components/grid/ch-grid-manager-selection.ts
  src/components/grid/ch-grid.tsx
Labels: fix, target: patch

#304 Add support for showing the development status of each control
  README.md
  src/components.d.ts
  src/components/checkbox/readme.md
  src/components/combobox/readme.md
  src/components/dropdown/readme.md
  src/components/flexible-layout/readme.md
  src/components/layout-splitter/readme.md
  src/components/radio-group/readme.md
  src/components/tree-view/readme.md
  src/index.html
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase.tsx
  src/showcase/models/components.js
Labels: documentation, target: major, showcase

#305 Add support for updating language direction and other improvements for showcase
  src/components/test/test-flexible-layout/renders.tsx
  src/components/test/test-flexible-layout/test-flexible-layout.scss
  src/index.html
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tree-view/models.ts
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/index.css
  src/showcase/models/language-manager.js
  src/showcase/models/theme-manager.js
  stencil.config.ts
Labels: documentation, target: patch, showcase

#306 Fix for disabled not working properly in `ch-combo-box` and add support for `destroyItemsOnClose` property
  src/components.d.ts
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/components/popover/popover.tsx
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
Labels: fix, feature, target: minor, accessibility, performance

#307 Improve consistency across all interfaces that implement a UI Model ("-render" controls)
  src/components.d.ts
  src/components/action-group/action-group-render.tsx
  src/components/action-group/types.ts
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/components/combobox/types.ts
  src/components/dropdown/dropdown-render.tsx
  src/components/dropdown/types.ts
  src/components/flexible-layout/flexible-layout-render.tsx
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/internal/flexible-layout/readme.md
  src/components/flexible-layout/internal/flexible-layout/types.ts
  src/components/flexible-layout/readme.md
  src/components/flexible-layout/utils.ts
  src/components/layout-splitter/add-sibling-item.ts
  src/components/layout-splitter/layout-splitter.tsx
  src/components/layout-splitter/readme.md
  src/components/layout-splitter/remove-item.ts
  src/components/layout-splitter/test/fixAndUpdateLayoutModel.spec.ts
  src/components/layout-splitter/test/sizesToGridTemplate.spec.ts
  src/components/layout-splitter/types.ts
  src/components/layout-splitter/utils.ts
  src/components/list/list.tsx
  src/components/list/readme.md
  src/components/radio-group/radio-group-render.tsx
  src/components/radio-group/readme.md
  src/components/radio-group/types.ts
  src/components/segmented-control/readme.md
  src/components/segmented-control/segmented-control-render.tsx
  src/components/segmented-control/types.ts
  src/components/test/test-flexible-layout/readme.md
  src/components/test/test-flexible-layout/renders.tsx
  src/components/test/test-flexible-layout/test-flexible-layout.tsx
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.tsx
  src/components/tree-view/types.ts
  src/index.html
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
  src/showcase/assets/components/dropdown/models.ts
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/layout-splitter/models.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/pages/radio-group.html
  src/showcase/pages/segmented-control.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/tree-view.html
Labels: target: major, breaking changes, refactoring, risky

#308 Reuse scripts in "build" and "start"
  package.json
Labels: fix, target: patch

#309 [ch-grid] The 'rowContextMenu' event was triggered upon clicking within the Grid, but outside of any specific row.
  src/components/common/helpers.ts
  src/components/grid/ch-grid.tsx
Labels: fix, target: patch

#310 Add support to render HTML in `ch-markdown` and improve DOM sanitizer
  src/components.d.ts
  src/components/markdown/markdown.tsx
  src/components/markdown/parsers/markdown-to-jsx.tsx
  src/components/markdown/parsers/raw-html-to-jsx.tsx
  src/components/markdown/readme.md
  src/showcase/pages/markdown.html
Labels: feature, target: minor

#311 Revert `rawHtml` default to "false"
  src/components/markdown/markdown.tsx
Labels: fix

#312 Fixes and improvements for `rawHTML` implementation in `ch-markdown`
  src/components/markdown/parsers/raw-html-to-jsx.tsx
Labels: fix, target: patch

#313 Add showcase URL in the readme file and add "development status" section in the landing page
  README.md
  src/index.html
  src/showcase/index.css
Labels: documentation, target: patch, showcase

#314 Always select ch-list's items on user interaction unless `defaultPrevented`. Also, add showcase story for the `ch-list` control
  src/components.d.ts
  src/components/list/list.tsx
  src/components/list/readme.md
  src/components/markdown/readme.md
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/tab/models.ts
  src/showcase/assets/components/tab/tab.showcase.tsx
  src/showcase/assets/components/tree-view/models.ts
  src/showcase/assets/components/types.ts
  src/showcase/base.css
  src/showcase/pages/tab.html
Labels: fix, target: patch, showcase

#315 Improve interface consistency, reactivity and accessibility in the `ch-qr` control
  src/components.d.ts
  src/components/qr/ch-qr.scss
  src/components/qr/ch-qr.tsx
  src/components/qr/qr.scss
  src/components/qr/qr.tsx
  src/components/qr/readme.md
  src/components/qr/types.ts
  src/showcase/assets/components/qr/qr.showcase.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
  src/showcase/models/components.js
  src/showcase/pages/qr.html
  stencil.config.ts
Labels: documentation, feature, target: major, accessibility, breaking changes, showcase

#316 [gx-grid] The grid pagination doesn't work when the RecordCount property is not specified
  src/components/gx-grid/gx-grid-chameleon.tsx
Labels: bug, target: patch

#319 In the `ch-combo-box`, use as the `min-inline-size` the size of the largest value and improve responsiveness
  src/components/combobox/combo-box.scss
  src/components/combobox/combo-box.tsx
  src/components/popover/utils.ts
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
Labels: fix

#320 Don't fire the `selectedItemChange` event on the `ch-segmented-control-render` control if the item is already selected
  src/components/segmented-control/internal/segmented-control-item/segmented-control-item.tsx
Labels: fix, target: patch

#321 Add support for using Mercury DS in the showcase
  src/components.d.ts
  src/index.html
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/slider/slider.showcase.tsx
  src/showcase/base.css
  src/showcase/models/ds-manager.js
  src/showcase/pages/accordion.html
  src/showcase/pages/action-group.html
  src/showcase/pages/alert.html
  src/showcase/pages/barcode-scanner.html
  src/showcase/pages/code-editor.html
  src/showcase/pages/dialog.html
  src/showcase/pages/flexible-layout.html
  src/showcase/pages/grid.html
  src/showcase/pages/markdown.html
  src/showcase/pages/notifications.html
  src/showcase/pages/paginator.html
  src/showcase/pages/popover.html
  src/showcase/pages/radio-group.html
  src/showcase/pages/segmented-control.html
  src/showcase/pages/select.html
  src/showcase/pages/shortcuts.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/textblock.html
  src/showcase/pages/tooltip.html
  src/showcase/pages/tree-view.html
Labels: target: patch, showcase

#322 Avoid FOUC on initial loading in the showcase
  src/showcase/models/ds-manager.js
Labels: showcase

#323 Fix Theia's bug when using Chrome 110 and displaying lines in the Tree VIew
  src/components/tree-view/internal/tree-view-item/tree-view-item.scss
Labels: fix, target: patch

#324 Improve Mercury styling
  src/index.html
  src/showcase/assets/components/showcase.scss
  src/showcase/base.css
  src/showcase/index.css
  src/showcase/pages/accordion.html
  src/showcase/pages/action-group.html
  src/showcase/pages/barcode-scanner.html
  src/showcase/pages/code-editor.html
  src/showcase/pages/dialog.html
  src/showcase/pages/markdown.html
  src/showcase/pages/notifications.html
  src/showcase/pages/popover.html
  src/showcase/pages/radio-group.html
  src/showcase/pages/segmented-control.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/step-list.html
  src/showcase/pages/tree-view.html
Labels: target: patch, showcase

#325 Add `ch-switch` control
  src/common/reserverd-names.ts
  src/components.d.ts
  src/components/switch/readme.md
  src/components/switch/switch.scss
  src/components/switch/switch.tsx
  src/components/switch/test/switch.e2e.ts
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/switch/switch.showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/models/components.js
Labels: feature, target: minor, showcase

#327 Improve support with web forms in `ch-checkbox` and upgrade its status to Developer Preview
  src/common/interfaces.ts
  src/components.d.ts
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
  src/showcase/assets/components/checkbox/checkbox.showcase.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/types.ts
  src/showcase/models/components.js
Labels: fix, feature, target: minor, accessibility, showcase

#328 Delete font rules that are no longer needed and update icons on landing page
  src/index.html
  src/showcase/base.css
  src/showcase/index.css
Labels: target: patch, showcase

#329 Add `ch-code` control
  src/components.d.ts
  src/components/code/code.scss
  src/components/code/code.tsx
  src/components/code/internal/code-highlight.tsx
  src/components/code/internal/types.ts
  src/components/code/readme.md
  src/index.html
  src/showcase/assets/components/code/code.showcase.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/base.css
  src/showcase/models/components.js
  stencil.config.ts
Labels: feature, target: minor, showcase

#330 `[ch-combo-box]` Add support for strict filters and solve the vast majority of keyboard issues
  src/components.d.ts
  src/components/action-group/readme.md
  src/components/combobox/combo-box.scss
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/components/combobox/types.ts
  src/components/popover/popover.tsx
  src/components/popover/readme.md
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
Labels: fix, feature, target: minor, accessibility

#331 House keeping
  src/common/reserved-names.ts
  src/components/action-group/action-group-render.tsx
  src/components/action-group/internal/action-group/action-group.tsx
  src/components/checkbox/checkbox.tsx
  src/components/combobox/combo-box.tsx
  src/components/dropdown/dropdown-render.tsx
  src/components/dropdown/internal/dropdown/dropdown.tsx
  src/components/dropdown/utils.ts
  src/components/next/data-modeling-item/next-data-modeling-item.tsx
  src/components/popover/popover.tsx
  src/components/radio-group/radio-group-render.tsx
  src/components/segmented-control/internal/segmented-control-item/segmented-control-item.tsx
  src/components/segmented-control/segmented-control-render.tsx
  src/components/switch/switch.tsx
  src/components/textblock/textblock.tsx
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/components/tree-view/internal/tree-view/tree-view.tsx
  src/components/tree-view/utils.ts
  src/index.html
  src/showcase/base.css
Labels: showcase

#332 Add initial implementation for the Action List control
  src/common/_icons.scss
  src/common/renders.tsx
  src/common/reserved-names.ts
  src/components/action-list/action-list-render.scss
  src/components/action-list/action-list-render.tsx
  src/components/action-list/internal/action-list-group/action-list-group.scss
  src/components/action-list/internal/action-list-group/action-list-group.tsx
  src/components/action-list/internal/action-list-item/action-list-item.scss
  src/components/action-list/internal/action-list-item/action-list-item.tsx
  src/components/action-list/internal/action-list-item/types.ts
  src/components/action-list/internal/readme.md
  src/components/action-list/types.ts
  src/showcase/assets/components/action-list/action-list.showcase.tsx
  src/showcase/assets/components/action-list/models.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
  src/showcase/base.css
  src/showcase/models/components.js
Labels: feature, target: minor

#333 Fix for exported types in action list
  src/components.d.ts
  src/components/action-list/internal/action-list-group/readme.md
  src/components/action-list/internal/action-list-item/readme.md
  src/components/action-list/readme.md
  src/components/action-list/types.ts
  src/components/next/data-modeling-item/readme.md
  src/components/next/data-modeling-render/readme.md
  src/components/tree-view/internal/tree-view/readme.md
  src/components/tree-view/readme.md
  src/showcase/assets/components/readme.md
Labels: fix
