Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-03, with the labels that each got.

#248 New features in `ch-flexible-layout` to expand modeling capabilities
  src/components.d.ts
  src/components/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/readme.md
  src/components/flexible-layout/types.ts
  src/components/layout-splitter/utils.ts
  src/components/list/list.scss
  src/components/renders/flexible-layout/flexible-layout-render.tsx
  src/components/renders/flexible-layout/readme.md
  src/components/renders/flexible-layout/utils.ts
  src/components/test/test-flexible-layout/renders.tsx
  src/showcase/pages/assets/models/tree.js
Labels: fix, feature, target: major, breaking changes, performance, refactoring

#249 General fixes and improvements
  src/components/list/list.scss
  src/components/markdown/parsers/code-highlight.tsx
  src/components/markdown/parsers/types.ts
  src/globals/design-systems/unanimo/base/_button.scss
  src/globals/design-systems/unanimo/base/_common.scss
  src/globals/design-systems/unanimo/base/_typography.scss
  src/globals/design-systems/unanimo/components/_markdown.scss
Labels: fix, feature, target: minor, refactoring

#250 Fix browser crash when expandable items are off screen
  src/components/tree-view/tree-view-item/tree-view-item.scss
Labels: fix, broken

#251 Various fixes for dropdown implementation
  src/components/dropdown/dropdown.scss
Labels: fix, target: patch

#253 Do not select or expand the tree-view-item on dblClick
  src/components/tree-view/tree-view-item/tree-view-item.tsx
Labels: fix, accessibility

#255 Various fixes for the ch-dropdown control
  src/components.d.ts
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/readme.md
  src/components/markdown/readme.md
  src/components/renders/action-group/action-group-render.tsx
  src/components/renders/dropdown/dropdown-render.tsx
Labels: fix, target: patch, performance, broken

#256 [ch-grid] Fix selection cases
  src/components/grid/ch-grid-manager-selection.ts
  src/components/grid/ch-grid.tsx
Labels: bug, target: patch

#257 Fixes and improvements for the `ch-checkbox` control
  src/components.d.ts
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
  src/components/checkbox/types.ts
  src/components/tree-view/tree-view-item/tree-view-item.scss
  src/components/tree-view/tree-view-item/tree-view-item.tsx
Labels: fix, feature, target: major, breaking changes, refactoring

#258 Add "ch-theme" component
  src/components.d.ts
  src/components/theme/readme.md
  src/components/theme/theme-stylesheet.ts
  src/components/theme/theme.tsx
Labels: feature, target: minor
