Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-07, with the labels that each got.

#355 Add methods and callbacks in the Action List control
  src/components/action-list/action-list-render.tsx
  src/components/action-list/internal/action-list-item/action-list-item.scss
Labels: fix, feature, target: major, accessibility

#356 Add support for multi-state icons in the Tree View control
  src/common/types.ts
  src/common/utils.ts
  src/components.d.ts
  src/components/action-list/readme.md
  src/components/tree-view/internal/tree-view-item/readme.md
  src/components/tree-view/internal/tree-view-item/tree-view-item.scss
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.tsx
  src/components/tree-view/types.ts
  src/index.html
  src/showcase/assets/components/tree-view/models.ts
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/base.css
Labels: feature, target: minor, target: major, breaking changes

#357 Add support to avoid FOUC in the ch-theme control
  src/components.d.ts
  src/components/theme/readme.md
  src/components/theme/theme.tsx
Labels: feature, target: minor

#358 Improve default properties in the Tree View control
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.tsx
Labels: target: major, breaking changes

#359 Fix Tree View icons not working if the "expanded" object was not specified
  src/common/utils.ts
Labels: fix, target: patch

#360 Add support for undefined images in `getImagePathCallback` of the Tree View control
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/components/tree-view/types.ts
  src/showcase/assets/components/tree-view/models.ts
Labels: feature, target: minor

#361 Add `ch-image` control
  src/components.d.ts
  src/components/image/image.scss
  src/components/image/image.tsx
  src/components/image/readme.md
  src/showcase/assets/components/image/image.showcase.tsx
  src/showcase/assets/components/image/models.ts
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
  src/showcase/base.css
  src/showcase/models/components.js
Labels: feature, target: minor

#362 Add support for undefined images in `getImagePathCallback` of the `ch-image` control
  src/components.d.ts
  src/components/image/image.tsx
Labels: feature, target: minor

#363 Fix DS update not working sometimes in the showcase
  src/showcase/assets/components/showcase.tsx
  src/showcase/base.css
Labels: showcase

#365 [ch-theme] Add model property
  src/components.d.ts
  src/components/theme/readme.md
  src/components/theme/theme-stylesheet.ts
  src/components/theme/theme-types.ts
  src/components/theme/theme.tsx
Labels: target: major, breaking changes

#366 Delete UI models when updating the Flexible Layout's model to avoid memory leak
  src/components.d.ts
  src/components/edit/readme.md
  src/components/flexible-layout/flexible-layout-render.tsx
Labels: fix, target: patch

#367 Add `registry-property.ts` module. A set of utilities for setting default values for the control properties.
  src/common/registry-properties.ts
  src/common/types.ts
  src/components.d.ts
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/image/image.tsx
  src/components/image/readme.md
  src/components/tree-view/internal/tree-view-item/tree-view-item.tsx
  src/components/tree-view/readme.md
  src/components/tree-view/tree-view-render.tsx
  src/index.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/assets/components/edit/models.ts
  src/showcase/assets/components/image/image.showcase.tsx
  src/showcase/assets/components/image/models.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tree-view/models.ts
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
Labels: feature, target: major

#368 Fix integration with other StencilJS libraries not working
  src/index.ts
Labels: fix, target: patch, broken

#369 Use CommonThemes instead of GlobalStyleSheet
  src/common/theme.ts
  src/components/tabular-grid/tabular-grid-manager.ts
  src/deprecated-components/window/ch-window.tsx
Labels: target: major, breaking changes

#371 Fixes and improvements for the `ch-flexible-layout-render` control
  src/components.d.ts
  src/components/flexible-layout/flexible-layout-render.tsx
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/readme.md
Labels: fix, feature, target: minor, broken

#372 Improve widget/item customization in the `ch-flexible-layout-render` and `ch-tab-render` controls
  src/common/types.ts
  src/components.d.ts
  src/components/flexible-layout/flexible-layout-render.tsx
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.scss
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/internal/flexible-layout/readme.md
  src/components/flexible-layout/internal/flexible-layout/types.ts
  src/components/flexible-layout/readme.md
  src/components/flexible-layout/utils.ts
  src/components/layout-splitter/layout-splitter.scss
  src/components/layout-splitter/layout-splitter.tsx
  src/components/layout-splitter/readme.md
  src/components/layout-splitter/remove-item.ts
  src/components/layout-splitter/types.ts
  src/components/tab/readme.md
  src/components/tab/tab.scss
  src/components/tab/tab.tsx
  src/components/tab/types.ts
  src/components/test/test-flexible-layout/renders.tsx
  src/components/test/test-flexible-layout/test-flexible-layout.scss
  src/components/test/test-flexible-layout/test-flexible-layout.tsx
Labels: fix, feature, target: minor

#373 Fixes for the ch-combo-box control on mobile devices
  src/components/combobox/combo-box.scss
  src/components/combobox/combo-box.tsx
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
Labels: fix, target: patch

#374 Rename the `ch-combo-box` control to `ch-combo-box-render`
  src/components.d.ts
  src/components/combobox/combo-box.tsx
  src/components/combobox/readme.md
  src/components/popover/readme.md
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/types.ts
  stencil.config.ts
Labels: target: minor, breaking changes

#375 Fix breaking changes in Design Systems
  src/components/test/test-flexible-layout/test-action-group-styles.scss
  src/components/test/test-flexible-layout/test-flexible-layout.scss
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/showcase.scss
  src/showcase/base.css
  src/showcase/index.css
  src/showcase/models/ds-manager.js
  src/showcase/pages/accordion.html
  src/showcase/pages/action-group.html
  src/showcase/pages/code-diff-editor.html
  src/showcase/pages/code-editor.html
  src/showcase/pages/notifications.html
  src/showcase/pages/sidebar.html
  src/showcase/pages/step-list.html
  src/showcase/pages/tree-view.html
Labels: showcase
