Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-10, with the labels that each got.

#425 Add `ch-tabular-grid-render` component
  src/components.d.ts
  src/components/tabular-grid-render/readme.md
  src/components/tabular-grid-render/tabular-grid-render.scss
  src/components/tabular-grid-render/tabular-grid-render.tsx
  src/components/tabular-grid-render/tests/tabular-grid-render.e2e.ts
  src/components/tabular-grid-render/types.ts
  src/components/tabular-grid/column/readme.md
  src/components/tabular-grid/columnset/readme.md
  src/components/tabular-grid/readme.md
  src/components/tabular-grid/rowset/legend/readme.md
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/tabular-grid-render/models.ts
  src/showcase/assets/components/tabular-grid-render/tabular-grid-render.showcase.tsx
  src/showcase/assets/components/types.ts
Labels: feature, target: minor

#426 Improve the column model of the tabular-grid-render.
  src/components.d.ts
  src/components/tabular-grid-render/tabular-grid-render.tsx
  src/components/tabular-grid-render/types.ts
  src/showcase/assets/components/tabular-grid-render/models.ts
Labels: feature, target: minor

#428 Various improvements and fixes for the `ch-combo-box-render` component
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/combo-box/combo-box.scss
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/navigation.ts
  src/components/combo-box/readme.md
  src/components/combo-box/tests/basic-behavior.e2e.ts
  src/components/combo-box/tests/combo-box.e2e.ts
  src/components/combo-box/tests/form.e2e.ts
  src/components/combo-box/tests/keyboard-selection-filters.e2e.ts
  src/components/combo-box/tests/keyboard-selection.e2e.ts
  src/components/combo-box/tests/normal-behavior.e2e.ts
  src/components/combo-box/tests/opening.e2e.ts
  src/components/combo-box/tests/parts.e2e.ts
  src/components/combo-box/tests/suggest-behavior.e2e.ts
  src/components/combo-box/utils.ts
  src/components/edit/tests/debounce.e2e.ts
  src/components/edit/tests/form.e2e.ts
  src/components/tabular-grid-render/readme.md
  src/components/theme/readme.md
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
  src/testing/form.e2e.ts
Labels: fix, feature, target: minor, accessibility, breaking changes, performance, refactoring

#429 `[ch-action-list-render]` Don't trigger `itemClick` or `selectedItemsChange` events if the item is being edited
  src/components/action-list/action-list-render.tsx
  src/components/action-list/tests/editing.e2e.ts
Labels: fix, target: patch

#430 `[ch-checkbox]` Add support to display an image, improve accessibility and reduce memory consumption
  src/common/registry-properties.ts
  src/common/types.ts
  src/components.d.ts
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/readme.md
  src/showcase/assets/components/checkbox/checkbox.showcase.tsx
  src/showcase/assets/components/showcase.tsx
Labels: feature, target: major, accessibility, breaking changes, performance, refactoring

#431 Fix React output integration with Vite build tool
  stencil.config.ts
Labels: fix

#433 `[ch-edit]` Add support to customize the clear button when `type="search"` and other improvements
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/edit/edit.scss
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/clear-button.e2e.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase.tsx
  src/showcase/base.css
Labels: fix, feature, target: minor, breaking changes, performance

#432 Add the attribute 'part' to the entities of TabularGridRender
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/tabular-grid-render/readme.md
  src/components/tabular-grid-render/tabular-grid-render.tsx
  src/components/tabular-grid-render/types.ts
  src/components/tabular-grid/cell/tabular-grid-cell.ts
  src/components/tabular-grid/column/readme.md
  src/components/tabular-grid/column/tabular-grid-column.tsx
  src/components/tabular-grid/columnset/readme.md
  src/components/tabular-grid/columnset/tabular-grid-columnset.tsx
  src/components/tabular-grid/row/tabular-grid-row.ts
  src/components/tabular-grid/rowset/legend/readme.md
  src/components/tabular-grid/rowset/legend/tabular-grid-rowset-legend.tsx
  src/components/tabular-grid/rowset/tabular-grid-rowset.tsx
  src/showcase/assets/components/tabular-grid-render/models.ts
  src/showcase/assets/components/tabular-grid-render/tabular-grid-render.showcase.tsx
Labels: feature, target: minor

#435 `[ch-combo-box-render]` Reflect the value of each item in the part and add the value prop as a part of the Host, if it matches an existing item
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/renders.tsx
Labels: feature, target: minor

#436 `[ch-markdown-viewer]` Add support for `showIndicator` property in the markdown-viewer when rendering `rawHTML`
  src/components/markdown-viewer/markdown-viewer.tsx
  src/components/markdown-viewer/parsers/markdown-to-jsx.tsx
  src/components/markdown-viewer/parsers/raw-html-to-jsx.tsx
  src/components/markdown-viewer/parsers/types.ts
  src/showcase/assets/components/markdown/markdown.showcase.tsx
Labels: feature

#437 Add support for specifying additional parts for the `ch-edit` and c`h-combo-box-render` Hosts
  src/components.d.ts
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/readme.md
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/edit/edit.showcase.tsx
Labels: feature, target: minor

#439 `[ch-action-list-render]` Fix `selection="single"` issues
  src/components/action-list/action-list-render.tsx
  src/components/action-list/selections.ts
  src/components/action-list/tests/selection.e2e.ts
  src/components/action-list/update-item-property.ts
  src/components/action-list/utils.ts
Labels: fix, target: patch

#440 `[ch-action-list-render]` Fix selection not working properly after updating the `model` reference
  src/components/action-list/action-list-render.tsx
  src/components/action-list/flatten-model.ts
  src/components/action-list/selections.ts
  src/components/action-list/tests/selection.e2e.ts
  src/components/action-list/utils.ts
Labels: fix, target: patch

#441 `[ch-action-list-render]` Add support to customize the scrollbar
  src/components/action-list/action-list-render.tsx
Labels: feature, target: minor

#442 `[ch-action-list-render]` Add `getImagePathCallback` property
  src/common/types.ts
  src/components.d.ts
  src/components/action-list/action-list-render.tsx
  src/components/action-list/internal/action-list-item/action-list-item.scss
  src/components/action-list/internal/action-list-item/action-list-item.tsx
  src/components/action-list/internal/action-list-item/readme.md
  src/components/action-list/readme.md
  src/components/action-list/types.ts
  src/showcase/assets/components/accordion/models.ts
  src/showcase/assets/components/action-list/action-list.showcase.tsx
  src/showcase/assets/components/action-list/models.tsx
  src/showcase/assets/components/showcase.tsx
Labels: feature, target: minor, breaking changes

#443 Optimize dev server startup times with the "start.optimized" script and reduce startup times of the "test.watch" script
  package.json
  stencil.config.optimized-dev.ts
  stencil.config.optimized-test-watch.ts
  stencil.config.ts
  tsconfig-optimized-dev.json
  tsconfig-optimized-test-watch.json
Labels: enhancement

#444 Untrack the `components.d.ts` file as it is generated in the CI/CD
  .gitignore
  src/components.d.ts
  tsconfig-optimized-dev.json
  tsconfig-optimized-test-watch.json
Labels: enhancement

#445 `[ch-combo-box-render]` Add support to render multi state images in the combo-box
  src/common/types.ts
  src/common/utils.ts
  src/components/combo-box/combo-box.scss
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/item-images.ts
  src/components/combo-box/renders.tsx
  src/components/combo-box/types.ts
  src/components/combo-box/utils.ts
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
  src/showcase/assets/components/showcase.tsx
Labels: fix, feature, target: minor

#448 `[ch-chat]` Remove unused "accessibleName.chat" translation
  src/components/chat/readme.md
  src/components/chat/translations.ts
  src/showcase/assets/components/chat/callbacks.ts
Labels: fix, target: patch, breaking changes

#449 `[ch-combo-box-render]` Fix icons not working when using `suggest` and `suggestOptions = { alreadyProcessed: true }`
  src/components/combo-box/combo-box.tsx
Labels: fix

#450 `[ch-combo-box-reder]` Add support for the change event
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/readme.md
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
Labels: feature, target: minor
