Repository genexuslabs/chameleon-controls-library, pull requests merged in 2024-08, with the labels that each got.

#376 Add support to disable the items of the `ch-tab-render` and `ch-flexible-layout-render`
  src/components.d.ts
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/internal/flexible-layout/types.ts
  src/components/flexible-layout/readme.md
  src/components/flexible-layout/utils.ts
  src/components/tab/readme.md
  src/components/tab/tab.tsx
  src/components/tab/types.ts
  src/components/test/test-flexible-layout/renders.tsx
  src/showcase/assets/components/tab/models.ts
  src/showcase/assets/components/tab/tab.showcase.tsx
Labels: feature, target: minor

#378 Refactor the entire implementation of the `ch-textblock` control
  package-lock.json
  package.json
  src/ResizeObserver.d.ts
  src/common/_base.scss
  src/common/line-clamp.ts
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/textblock/readme.md
  src/components/textblock/textblock.scss
  src/components/textblock/textblock.tsx
  src/showcase/assets/components/readme.md
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/textblock/textblock.showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/models/components.js
  stencil.config.ts
Labels: feature, target: minor, breaking changes, performance, refactoring, dependencies

#379 Add support for `updateItemProperties` method in the Action List control
  src/components.d.ts
  src/components/action-list/action-list-render.tsx
  src/components/action-list/readme.md
  src/components/action-list/update-item-property.ts
Labels: feature

#381 Include failed theme load errors in the final output of the `ch-theme`
  src/components/theme/theme.tsx
Labels: fix

#382 Improve default values and property names in `ch-tab-render` and `ch-flexible-layout-render` controls
  src/components.d.ts
  src/components/flexible-layout/flexible-layout-render.tsx
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/flexible-layout/internal/flexible-layout/readme.md
  src/components/flexible-layout/internal/flexible-layout/types.ts
  src/components/flexible-layout/readme.md
  src/components/flexible-layout/utils.ts
  src/components/tab/readme.md
  src/components/tab/tab.tsx
  src/components/test/test-flexible-layout/renders.tsx
  src/components/test/test-flexible-layout/test-flexible-layout.tsx
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tab/tab.showcase.tsx
Labels: feature, target: minor, breaking changes

#383 Fix tab closing issues in the `ch-tab-render` and `ch-flexible-layout-render` controls. Also, reduce memory usage.
  src/components/flexible-layout/internal/flexible-layout/flexible-layout.tsx
  src/components/tab/tab.tsx
  src/components/tab/utils.ts
  src/components/test/test-flexible-layout/renders.tsx
  src/components/test/test-flexible-layout/test-flexible-layout.scss
  src/index.html
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tab/tab.showcase.tsx
  src/showcase/index.css
Labels: fix, target: patch, breaking changes, performance, refactoring, showcase

#384 Fix `white-space` in the `ch-code`
  src/components/code/code.scss
  src/components/code/tests/code.e2e.ts
Labels: fix

#385 Run e2e tests on CI and fix `ch-edit`'s accessibility issue
  package.json
  src/components/action-group/internal/test/action-group-item.e2e.ts
  src/components/action-group/internal/test/action-group.e2e.ts
  src/components/edit/edit.tsx
  src/components/edit/tests/edit.e2e.ts
  src/components/intersection-observer/test/intersection-observer.e2e.ts
  src/components/intersection-observer/test/intersection-observer.spec.tsx
  src/components/suggest/suggest-list-item/test/ch-suggest-list-item.e2e.ts
  src/components/suggest/suggest-list-item/test/ch-suggest-list-item.spec.tsx
  src/components/suggest/suggest-list/test/ch-suggest-list.spec.tsx
  src/components/suggest/test/ch-suggest.e2e.ts
  src/components/suggest/test/ch-suggest.spec.tsx
  src/components/switch/test/switch.e2e.ts
  src/testing/form.e2e.ts
  src/testing/utils.e2e.ts
  stencil.config.ts
Labels: enhancement, fix, target: patch, accessibility

#387 Don't display the combo-box's picker when using suggest mode
  package.json
  src/components/code/tests/code.e2e.ts
  src/components/combo-box/combo-box.scss
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/tests/normal-behavior.e2e.ts
  src/components/combo-box/tests/suggest-behavior.e2e.ts
  src/testing/constants.e2e.ts
Labels: fix

#388 Fix flaky tests
  package.json
Labels: fix

#389 [ch-theme ] Fix themes that were rejected after they were correctly resolved
  src/components/theme/theme-stylesheet.ts
Labels: fix, target: patch

#390 Add a scrollbar in the `ch-combo-box-render` if the content overflows
  src/common/reserved-names.ts
  src/components.d.ts
  src/components/combo-box/combo-box.scss
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/readme.md
  src/components/popover/popover.scss
  src/components/popover/popover.tsx
  src/components/popover/readme.md
  src/components/popover/tests/styling.e2e.ts
  src/components/popover/utils.ts
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/tab/tab.showcase.tsx
  src/showcase/scrollbar.css
  src/testing/utils.e2e.ts
Labels: feature, target: minor, accessibility, breaking changes

#391 Fix `ch-theme` error when setting an empty model
  src/components/popover/tests/styling.e2e.ts
  src/components/theme/tests/theme.e2e.ts
  src/components/theme/theme.tsx
Labels: fix

#392 Refactor the `ch-combo-box-render` interface to rename `filter*` properties to `suggest*`
  src/components.d.ts
  src/components/combo-box/combo-box.tsx
  src/components/combo-box/helpers.ts
  src/components/combo-box/readme.md
  src/components/combo-box/tests/combo-box.e2e.ts
  src/components/combo-box/tests/normal-behavior.e2e.ts
  src/components/combo-box/tests/suggest-behavior.e2e.ts
  src/components/combo-box/types.ts
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/combo-box/models.ts
  src/showcase/assets/components/popover/models.ts
Labels: target: patch, accessibility, breaking changes, refactoring

#395 Depreacte the `ch-suggest` component
  src/components.d.ts
  src/deprecated-components/suggest/ch-suggest.scss
  src/deprecated-components/suggest/ch-suggest.tsx
  src/deprecated-components/suggest/notes.txt
  src/deprecated-components/suggest/readme.md
  src/deprecated-components/suggest/suggest-list-item/ch-suggest-list-item.scss
  src/deprecated-components/suggest/suggest-list-item/ch-suggest-list-item.tsx
  src/deprecated-components/suggest/suggest-list-item/readme.md
  src/deprecated-components/suggest/suggest-list-item/test/ch-suggest-list-item.e2e.ts
  src/deprecated-components/suggest/suggest-list-item/test/ch-suggest-list-item.spec.tsx
  src/deprecated-components/suggest/suggest-list/ch-suggest-list.scss
  src/deprecated-components/suggest/suggest-list/ch-suggest-list.tsx
  src/deprecated-components/suggest/suggest-list/readme.md
  src/deprecated-components/suggest/suggest-list/test/ch-suggest-list.e2e.ts
  src/deprecated-components/suggest/suggest-list/test/ch-suggest-list.spec.tsx
  src/deprecated-components/suggest/test/ch-suggest.e2e.ts
  src/deprecated-components/suggest/test/ch-suggest.spec.tsx
  src/deprecated-components/test/test-suggest/helpers.ts
  src/deprecated-components/test/test-suggest/readme.md
  src/deprecated-components/test/test-suggest/renderSuggest.tsx
  src/deprecated-components/test/test-suggest/test-suggest.css
  src/deprecated-components/test/test-suggest/test-suggest.tsx
  src/deprecated-components/window/readme.md
Labels: target: patch, breaking changes

#396 Fix `filterType = "list"` implementation in the `ch-tree-view-render` component
  src/components.d.ts
  src/components/tree-view/readme.md
  src/components/tree-view/tests/filters-filterType-list.e2e.ts
  src/components/tree-view/tests/render.e2e.ts
  src/components/tree-view/tree-view-render.tsx
Labels: fix, target: minor, breaking changes

#397 Improvements for the `ch-accordion-render`
  src/components.d.ts
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.tsx
  src/components/accordion/readme.md
  src/components/accordion/tests/accordion.e2e.ts
  src/components/code/tests/code.e2e.ts
  src/components/combo-box/tests/normal-behavior.e2e.ts
  src/components/combo-box/tests/suggest-behavior.e2e.ts
  src/components/popover/tests/styling.e2e.ts
  src/showcase/assets/components/accordion/accordion.showcase.tsx
  src/showcase/assets/components/accordion/models.ts
  src/testing/form.e2e.ts
Labels: fix, target: patch, accessibility, performance

#399 Add support to style the ch-code's scrollbar
  src/components/code/code.tsx
  src/showcase/assets/components/radio-group/models.ts
  src/showcase/assets/components/radio-group/radio-group.showcase.tsx
  src/showcase/scrollbar.css
Labels: feature, target: minor

#398 [ch-tabular-grid] Update implementantion to support scrollbars styling
  src/components/tabular-grid/tabular-grid.tsx
  src/deprecated-components/window/ch-window.tsx
Labels: target: patch, refactoring

#400 [ch-theme] Add properties to indicate if the theme must be attached to the Document or the ShadowRoot
  src/components.d.ts
  src/components/theme/readme.md
  src/components/theme/theme-types.ts
  src/components/theme/theme.tsx
Labels: feature, target: minor

#401 Improve the customization of the `ch-action-list-render` and add support to export parts for additional items
  src/common/_icons.scss
  src/components.d.ts
  src/components/action-list/internal/action-list-item/action-list-item.scss
  src/components/action-list/internal/action-list-item/action-list-item.tsx
  src/components/action-list/internal/action-list-item/compute-exportparts.ts
  src/components/action-list/internal/action-list-item/readme.md
  src/showcase/assets/components/action-list/action-list.showcase.tsx
  src/showcase/assets/components/action-list/models.tsx
Labels: fix, target: patch

#402 Make code examples reactive to state changes
  src/showcase/assets/components/accordion/accordion.showcase.tsx
  src/showcase/assets/components/barcode-scanner/barcode-scanner.showcase.tsx
  src/showcase/assets/components/checkbox/checkbox.showcase.tsx
  src/showcase/assets/components/code/code.showcase.tsx
  src/showcase/assets/components/combo-box/combo-box.showcase.tsx
  src/showcase/assets/components/dialog/dialog.showcase.tsx
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/assets/components/image/image.showcase.tsx
  src/showcase/assets/components/layout-splitter/layout-splitter.showcase.tsx
  src/showcase/assets/components/popover/popover.showcase.tsx
  src/showcase/assets/components/qr/qr.showcase.tsx
  src/showcase/assets/components/radio-group/radio-group.showcase.tsx
  src/showcase/assets/components/segmented-control/segmented-control.showcase.tsx
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/slider/slider.showcase.tsx
  src/showcase/assets/components/switch/switch.showcase.tsx
  src/showcase/assets/components/tab/tab.showcase.tsx
  src/showcase/assets/components/tree-view/tree-view.showcase.tsx
  src/showcase/assets/components/types.ts
  src/showcase/assets/components/utils.ts
Labels: showcase

#403 Fix selection not working in the `ch-action-list-render` when setting `selection = "single"` by default
  src/components/action-list/action-list-render.tsx
  src/components/action-list/tests/action-list.e2e.ts
Labels: fix, target: patch
