Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-04, with the labels that each got.

#496 `[ch-tree-view-render]` Fixes for interactions with the checkbox and filters with `filterType="list"`
  src/components/checkbox/checkbox.tsx
  src/components/tree-view/tests/events/checkedItemsChange.e2e.ts
  src/components/tree-view/tests/filters-filterType-list.e2e.ts
  src/components/tree-view/tests/utils.e2e.ts
  src/components/tree-view/tree-view-render.tsx
Labels: fix, target: patch

#497 Fix closing the `ch-dialog` when a `ch-layout-splitter` bar is resized
  src/components/layout-splitter/layout-splitter.scss
  src/components/layout-splitter/layout-splitter.tsx
  src/showcase/assets/components/dialog/dialog.showcase.tsx
Labels: fix, target: patch

#494 `[ch-chat]` Add support for `validateSendChatMessage` callback
  src/components/chat/chat.tsx
  src/components/chat/readme.md
  src/components/chat/tests/callbacks/validateSendChatMessage.e2e.ts
  src/components/chat/types.ts
Labels: feature, target: minor

#498 Fix RTL not working propertly in `ch-action-menu-render`, `ch-combo-box-render`, `ch-dialog`, and `ch-popover` components
  src/components/dialog/dialog.tsx
  src/components/popover/popover.scss
  src/components/popover/popover.tsx
Labels: fix, target: patch, accessibility, performance, refactoring

#499 `[ch-combo-box-render][ch-sidebar]` Correctly position the icons of the `ch-combo-box-render` and `ch-sidebar` components when `dir="rtl"`
  src/common/_icons.scss
  src/components/combo-box/combo-box.scss
  src/components/sidebar/readme.md
  src/components/sidebar/sidebar.scss
  src/components/sidebar/sidebar.tsx
Labels: fix, target: patch, accessibility

#500 Add `ch-progress` component
  package.json
  src/components/progress/constants.ts
  src/components/progress/progress.scss
  src/components/progress/progress.tsx
  src/components/progress/tests/basic.e2e.ts
  src/framework-integrations.ts
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/progress/progress.showcase.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
  src/testing/general/analyzeLabelExistence.e2e.ts
Labels: feature, target: minor, accessibility

#501 `[ch-chat]` Add support for positioning the scroll in new ways when adding messages by user interaction
  src/common/types.ts
  src/components/chat/chat.tsx
  src/components/chat/readme.md
  src/components/chat/tests/basic.e2e.ts
  src/components/chat/tests/items-reactivity.e2e.ts
  src/components/chat/tests/scroll.e2e.ts
  src/components/notifications/notifications.tsx
  src/components/progress/readme.md
  src/components/smart-grid/calculate-space-to-reserve.ts
  src/components/smart-grid/internal/infinite-scroll/infinite-scroll.tsx
  src/components/smart-grid/internal/infinite-scroll/readme.md
  src/components/smart-grid/internal/smart-grid-cell/readme.md
  src/components/smart-grid/internal/smart-grid-cell/smart-grid-cell.scss
  src/components/smart-grid/internal/smart-grid-cell/smart-grid-cell.tsx
  src/components/smart-grid/readme.md
  src/components/smart-grid/smart-grid.scss
  src/components/smart-grid/smart-grid.tsx
  src/components/smart-grid/tests/basic.e2e.ts
  src/components/smart-grid/tests/methods/scrollEndContentToPosition.e2e.ts
  src/components/virtual-scroller/cells-in-viewport-are-rendered-and-visible.ts
  src/components/virtual-scroller/get-new-start-and-end-indexes.ts
  src/components/virtual-scroller/readme.md
  src/components/virtual-scroller/types.ts
  src/components/virtual-scroller/update-virtual-scroll.ts
  src/components/virtual-scroller/utils.ts
  src/components/virtual-scroller/virtual-scroller.scss
  src/components/virtual-scroller/virtual-scroller.tsx
  src/framework-integrations.ts
  src/showcase/assets/components/chat/callbacks.ts
  src/showcase/assets/components/chat/chat.showcase.tsx
Labels: feature, target: minor, accessibility

#502 Add `ch-live-kit-room` component
  package-lock.json
  package.json
  src/components/live-kit-room/connect.ts
  src/components/live-kit-room/live-kit-room.scss
  src/components/live-kit-room/live-kit-room.tsx
  src/components/live-kit-room/readme.md
  src/components/live-kit-room/types.ts
  src/showcase/assets/components/live-kit-room/callbacks.ts
  src/showcase/assets/components/live-kit-room/live-kit-room.showcase.tsx
  src/showcase/assets/components/live-kit-room/models.ts
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
Labels: feature, target: minor

#504 `[ch-chat]` Refactor the `ch-chat` interface to improve consistency and extensibility. Add support for uploading and rendering files
  src/common/mimeTypes/mime-types-utils.ts
  src/common/mimeTypes/mime-types.ts
  src/common/types.ts
  src/components/chat/chat.scss
  src/components/chat/chat.tsx
  src/components/chat/default-chat-render.tsx
  src/components/chat/renders/actions.tsx
  src/components/chat/renders/code-block.tsx
  src/components/chat/renders/content.tsx
  src/components/chat/renders/file.tsx
  src/components/chat/renders/renders.tsx
  src/components/chat/renders/source.tsx
  src/components/chat/renders/structure.tsx
  src/components/chat/tests/basic.e2e.ts
  src/components/chat/tests/callbacks/validateSendChatMessage.e2e.ts
  src/components/chat/tests/items-reactivity.e2e.ts
  src/components/chat/tests/smart-grid.e2e.ts
  src/components/chat/translations.ts
  src/components/chat/types.ts
  src/components/chat/utils.ts
  src/showcase/assets/components/chat/callbacks.ts
  src/showcase/assets/components/chat/chat.showcase.tsx
  src/showcase/assets/components/chat/mercury-code-render.tsx
Labels: documentation, fix, feature, target: minor, accessibility, breaking changes, refactoring

#505 `[ch-chat][ch-edit]` Add support for adding additional content inside the `ch-edit` and `ch-chat`'s send-input
  copy-files.mjs
  package-lock.json
  package.json
  src/common/mimeTypes/mime-types-utils.ts
  src/common/mimeTypes/mime-types.ts
  src/components/chat/chat.scss
  src/components/chat/chat.tsx
  src/components/chat/readme.md
  src/components/chat/renders/structure.tsx
  src/components/chat/tests/basic.e2e.ts
  src/components/chat/tests/callbacks/validateSendChatMessage.e2e.ts
  src/components/chat/tests/items-reactivity.e2e.ts
  src/components/chat/types.ts
  src/components/edit/edit.scss
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/live-kit-room/readme.md
  src/framework-integrations.ts
  src/showcase/assets/components/chat/chat.showcase.tsx
  src/showcase/assets/components/edit/edit.showcase.tsx
  src/showcase/showcase-flexible-layout.css
Labels: fix, feature, target: minor, breaking changes, refactoring
