Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-06, with the labels that each got.

#515 `[ch-edit]` Add support for `showPassword` and `showPasswordButton` properties and move translations into the `translations` property
  src/common/_icons.scss
  src/common/reserved-names.ts
  src/components/edit/edit.scss
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/basic.e2e.ts
  src/components/edit/tests/edit.e2e.ts
  src/components/edit/tests/showPassword.e2e.ts
  src/components/edit/tests/showPasswordButton.e2e.ts
  src/components/edit/types.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
Labels: feature, target: minor, accessibility, breaking changes

#517 `[ch-chat]` Reduce flickering in the virtual scroll
  src/components/chat/chat.scss
Labels: fix, target: patch, broken

#519 Fix `ch-barcode-scanner` component not working when rendered as hidden
  src/components/barcode-scanner/barcode-scanner.tsx
  src/showcase/assets/components/barcode-scanner/barcode-scanner.showcase.tsx
  src/showcase/assets/components/showcase.scss
  src/showcase/assets/components/showcase.tsx
Labels: fix, target: patch

#522 `[ch-action-menu-render]` Add support for positionTry property to improve positioning when the content overflows the window.
  src/components/action-menu/action-menu-render.tsx
  src/components/action-menu/internal/action-menu/action-menu.tsx
  src/components/action-menu/internal/action-menu/readme.md
  src/components/action-menu/readme.md
  src/components/action-menu/types.ts
  src/components/popover/popover.tsx
  src/components/popover/readme.md
  src/showcase/assets/components/action-menu/action-menu.showcase.tsx
  src/showcase/assets/components/popover/popover.showcase.tsx
Labels: feature, target: minor, accessibility

#503 Improvements on accessibility and translations in the `paginator-render` component
  src/common/reserved-names.ts
  src/components/paginator-render/paginator-render.scss
  src/components/paginator-render/paginator-render.tsx
  src/components/paginator-render/readme.md
  src/components/paginator-render/tests/accessibility.e2e.ts
  src/components/paginator-render/tests/basic.e2e.ts
  src/components/paginator-render/tests/disabled.e2e.ts
  src/components/paginator-render/tests/model.e2e.ts
  src/components/paginator-render/tests/order.e2e.ts
  src/components/paginator-render/translations.ts
  src/components/paginator-render/types.ts
  src/showcase/assets/components/paginator-render/models.ts
  src/showcase/assets/components/paginator-render/paginator-render.showcase.tsx
Labels: fix, feature, target: minor, accessibility, breaking changes

#523 `[ch-code]` Add basic support for GeneXus language
  package-lock.json
  package.json
Labels: feature, target: minor

#520 Add `ch-status` component
  src/components/status/status.scss
  src/components/status/status.tsx
  src/components/status/tests/accessibility.e2e.ts
  src/components/status/tests/basic.e2e.ts
  src/framework-integrations.ts
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/status/status.showcase.tsx
  src/showcase/assets/components/types.ts
Labels: feature, target: minor, accessibility
