Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-05, with the labels that each got.

#506 `[ch-edit]` Fix clear button not displaying properly
  src/components/edit/edit.scss
Labels: fix, target: patch

#508 `[ch-accordion-render]` Add support to customize the position of the expandable button with the `expandableButtonPosition` property
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.tsx
  src/components/accordion/readme.md
  src/showcase/assets/components/accordion/accordion.showcase.tsx
Labels: feature, target: minor

#509 Add `ch-rating` component
  src/components/rating/rating.scss
  src/components/rating/rating.tsx
  src/components/rating/readme.md
  src/components/rating/tests/basic.e2e.ts
  src/framework-integrations.ts
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/rating/rating.showcase.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
  src/testing/general/analyzeLabelExistence.e2e.ts
Labels: feature, target: minor, accessibility

#510 `[ch-popover]` Add support to prevent the `popoverOpened` and `popoverClosed` events
  src/components/popover/popover.tsx
  src/components/popover/readme.md
Labels: feature, target: minor
