Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-03, with the labels that each got.

#491 `[ch-tab-render]` Add support for multi state icons in the tab component
  package-lock.json
  src/common/types.ts
  src/components/smart-grid/readme.md
  src/components/tab/readme.md
  src/components/tab/tab.scss
  src/components/tab/tab.tsx
  src/components/test/test-flexible-layout/renders.tsx
  src/showcase/assets/components/accordion/models.ts
  src/showcase/assets/components/showcase.tsx
  src/showcase/assets/components/tab/models.ts
Labels: fix, feature, target: minor

#493 [ch-chat] Add stopGeneratingAnswerButton to accessibleName and text in ChatTranslations type
  src/components/chat/chat.tsx
  src/components/chat/readme.md
  src/components/chat/tests/basic.e2e.ts
  src/components/chat/translations.ts
  src/showcase/assets/components/chat/callbacks.ts
Labels: feature, target: minor, accessibility, breaking changes

#475 Add `[paginator-render]` component
  src/common/reserved-names.ts
  src/components/combo-box/readme.md
  src/components/paginator-render/constants.ts
  src/components/paginator-render/paginator-render.scss
  src/components/paginator-render/paginator-render.tsx
  src/components/paginator-render/readme.md
  src/components/paginator-render/translations.ts
  src/components/paginator-render/types.ts
  src/framework-integrations.ts
  src/showcase/assets/components/pages.ts
  src/showcase/assets/components/paginator-render/models.ts
  src/showcase/assets/components/paginator-render/paginator-render.showcase.tsx
  src/showcase/assets/components/showcase-stories.ts
  src/showcase/assets/components/types.ts
Labels: feature, target: minor
