Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-01, with the labels that each got.

#469 `[ch-dialog][ch-popover]` Rename property name `hidden` to `show`
  src/components/combo-box/combo-box.tsx
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
  src/components/dialog/tests/accessibility.e2e.ts
  src/components/dialog/tests/basic.e2e.ts
  src/components/dropdown/internal/dropdown/dropdown.tsx
  src/components/popover/popover.scss
  src/components/popover/popover.tsx
  src/components/popover/readme.md
  src/components/tooltip/tooltip.tsx
  src/showcase/assets/components/dialog/dialog.showcase.tsx
  src/showcase/assets/components/popover/popover.showcase.tsx
Labels: fix, target: minor, breaking changes

#470 Fix flaky tests
  src/components/action-list/tests/selection.e2e.ts
  src/showcase/assets/components/action-list/models.tsx
Labels: fix

#471 `[ch-tab-render]` Add support to render slots for the start and end of the tab-list
  src/common/reserved-names.ts
  src/components/flexible-layout/tests/slots.e2e.ts
  src/components/tab/tab.scss
  src/components/tab/tab.tsx
  src/components/tab/tests/basic.e2e.ts
  src/components/tab/tests/tab-list.e2e.ts
  src/showcase/assets/components/tab/tab.showcase.tsx
Labels: feature, target: minor

#472 `[ch-slider]` Fix disabled support
  src/components/slider/slider.scss
  src/components/slider/slider.tsx
  src/components/slider/tests/disabled.e2e.ts
Labels: fix, target: patch, performance

#473 `[ch-action-list-render]` Fix `ch-action-list-render` not working with Angular SSR in some edge cases
  src/components/action-list/action-list-render.tsx
Labels: fix, target: patch

#474 Fixed `registerProperty` implementation not working in some frameworks
  src/common/registry-properties.ts
  src/components/navigation-list/navigation-list-render.tsx
Labels: fix, target: patch

#476 `[ch-combo-box-render]` Fix emitting the value with debounce, even when the selection is confirmed with no strict filters
  src/components/combo-box/combo-box.tsx
Labels: fix, target: patch
