Repository genexuslabs/chameleon-controls-library, pull requests merged in 2025-07, with the labels that each got.

#525 Fix `ch-status`, added missing README file and updated `ch-paginator-render` README
  src/components/paginator-render/readme.md
  src/components/status/readme.md
Labels: documentation, fix, target: patch

#527 `[ch-dialog]` Add support to `preventDefault` the `dialogClosed` event and fix `dialogClosed` not being fired when clicking the close button
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
  src/components/popover/popover.tsx
Labels: fix, feature, target: minor, accessibility, performance

#528 Fix the `ch-popover` component that would error in some scenarios when detached from the DOM
  src/components/popover/popover.tsx
Labels: fix, target: patch

#533 `[ch-dialog]` Add support for disabling close actions
  src/components/dialog/dialog.tsx
  src/components/dialog/readme.md
  src/showcase/assets/components/dialog/dialog.showcase.tsx
Labels: feature, target: minor

#535 Fix `ch-markdown-viewer` that was adding white spaces in the rendered content
  .prettierignore
  src/components/markdown-viewer/markdown-viewer.scss
  src/components/markdown-viewer/parsers/renders.lit.ts
  src/components/markdown-viewer/tests/basic.e2e.ts
Labels: fix

#536 `[ch-edit]` Add support to don't fire the `keydown` event when pressing the Enter in the Input Mode Editor
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/edit/tests/basic.e2e.ts
  src/components/edit/tests/preventEnterInInputEditorMode.e2e.ts
  src/showcase/assets/components/edit/edit.showcase.tsx
Labels: documentation, feature, target: minor, accessibility

#538 Fix `ch-popover` not updating its position when scrolling inside a projected slot
  src/common/get-all-root-nodes.ts
  src/common/tests/get-all-root-nodes.e2e.ts
  src/components/popover/popover.tsx
Labels: fix, target: patch, accessibility
